# Generated by Django 4.0.5 on 2022-06-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoViajesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursion',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vuelo',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='duracion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
