# Generated by Django 4.0.5 on 2022-07-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoViajesApp', '0005_acerca_de'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('approved_comment', models.BooleanField(default=False)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ProyectoViajesApp.excursion')),
            ],
        ),
    ]
