# Generated by Django 4.0.5 on 2022-07-25 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProyectoViajesApp', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ProyectoViajesApp.excursion')),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
